local-sim:
  user-workflow:
    workflow-name: "eros-resolution-sim"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.local-sim.json"
    secrets-path: "../secrets.local-sim.yaml"
staging:
  user-workflow:
    workflow-name: "eros-resolution-stg"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
production:
  user-workflow:
    workflow-name: "eros-resolution"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"

fresh-testnet:
  user-workflow:
    workflow-name: "eros-resolution-sim"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.fresh-testnet.json"
    secrets-path: "../secrets.local-sim.yaml"
