import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy policy", description: "How the Eros Markets testnet uses wallet data, browser storage, and third-party services." };

export default function PrivacyPage() {
  return <LegalPage eyebrow="Your data" title="Privacy policy" intro="This notice describes the current Eros Markets testnet website. It explains what the app handles when you browse, connect a wallet, or use a trading feature." sections={[
    { id: "data", title: "Information the app handles", body: <><p>Public market data can be viewed without signing in. When you connect, the app handles your wallet address, network, public balances, orders, positions, and transaction hashes to display your account and submit actions you request.</p><p>Sign-in is provided by Privy. Depending on your chosen method, Privy processes your email address, Google account information, or wallet sign-in details. Optional server features use your Privy identity and wallet address to verify permissions. Never send the project team a seed phrase or private key.</p></> },
    { id: "purposes", title: "Why this information is used", body: <><p>We use this information to operate sign-in and wallet features, show market and account activity, verify transaction permissions, process requested actions, and diagnose service failures.</p><p>If enabled and authorized by you, one-click trading and background protection store permission records, rule settings, request identifiers, transaction hashes, and execution logs. These features do not run merely because you visit a page.</p></> },
    { id: "browser-storage", title: "Cookies & browser storage", body: <><p>Privy and wallet connection services use cookies or similar storage for authentication, sessions, and wallet functionality. Their storage behavior is governed by their own services and policies.</p><ul><li><strong>Theme:</strong> <code>eros-theme</code> remembers your light, dark, or system choice.</li><li><strong>Order discovery:</strong> keys beginning <code>eros-orders:</code> keep recent order IDs by chain, market, and wallet. Contract reads remain authoritative.</li><li><strong>This notice:</strong> <code>eros-cookie-notice-v1</code> remembers acknowledgement for 180 days. This is not permission for advertising or analytics.</li></ul><p>Eros has not configured advertising pixels or optional analytics tools in this version. You can reopen the notice from “Cookies & storage” in the footer. Browser settings can clear or block storage; doing so may reset preferences, sign you out, or remove locally remembered order IDs. It does not remove blockchain records or revoke on-chain permissions.</p></> },
    { id: "providers", title: "Services that receive information", body: <><p>The site uses Privy for authentication and wallet infrastructure, Monad RPC providers for blockchain reads and transaction submission, and an indexer when configured for market history. Hosting and these providers may receive technical request information, such as IP address, browser details, and the wallet addresses included in requests.</p><p>External wallets, Google sign-in, explorers, and linked services have their own policies. Read <a href="https://www.privy.io/privacy-policy" target="_blank" rel="noreferrer">Privy’s privacy policy</a> for its handling of personal information. Following an external link sends you to that service.</p></> },
    { id: "public-records", title: "Public blockchain records", body: <p>Wallet addresses and submitted transactions are public. Others can associate activity with an address and may link it to your identity. Blockchain records generally cannot be edited or deleted by Eros, including after you disconnect a wallet or request deletion of off-chain data. Do not put private information in public evidence links or transaction data.</p> },
    { id: "retention", title: "Retention & your choices", body: <><p>Theme and order records stay in your browser until cleared. The cookie notice is shown again after its acknowledgement expires. Where server-side trading or protection is configured, operational records remain in the service database; this version does not implement automatic deletion of those records.</p><p>You can disconnect or log out, revoke available trading permissions, cancel protection rules, and clear browser storage. Depending on applicable law, you may have rights to access, correct, delete, or restrict use of personal information, or complain to a data-protection authority. Third-party account requests may also need to be made directly to the relevant provider.</p></> },
    { id: "contact", title: "Questions & updates", body: <><p>For privacy requests, contact the Eros Markets project team through the channel where you received access to this testnet. Share only the minimum information needed to identify your request; do not post account details or sensitive information in public issues.</p><p>We will update this page when the app’s data practices change. The date above identifies this version. See also the <Link href="/terms">terms of use</Link>.</p></> },
  ]} />;
}
