import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms of use", description: "Terms for using the Eros Markets experimental Monad testnet." };

export default function TermsPage() {
  return <LegalPage eyebrow="Before you trade" title="Terms of use" intro="Eros Markets is an experimental interface for event markets on Monad testnet. These terms describe the current demo and the responsibilities that come with using it." sections={[
    { id: "scope", title: "The testnet service", body: <><p>This version is provided for evaluation and testing. Its collateral is a test token, not USDC, and Eros makes no promise that test tokens, points, or participation can be redeemed for money, rewards, or future tokens.</p><p>Markets marked as fixtures use test scenarios. The currently configured fixture resolves through a manual test authority. Treat its prices, outcomes, and demo calculations as test behavior, not evidence about a real-world event.</p></> },
    { id: "eligibility", title: "Your use of the site", body: <p>Use the service only if you can lawfully do so in your jurisdiction and have authority to use the connected wallet. Do not use the site for unlawful activity, attempt to access another person’s account, interfere with other users, or misrepresent test results. Report defects without exploiting other users or exposing their information.</p> },
    { id: "wallets", title: "Wallets & permissions", body: <><p>You are responsible for the wallet you connect, the account and network you select, and the transactions you approve. Protect your credentials and review contract addresses, amounts, and permissions before signing. Transactions may be irreversible and can incur network fees even when they fail.</p><p>Privy can create an embedded wallet or connect an existing wallet. One-click trading and background protection require separate permissions when available. Review and revoke these permissions through the provided controls. Disconnecting a wallet alone does not revoke every permission or cancel an existing order.</p><p>Privy’s services are also subject to its <a href="https://www.privy.io/user-terms-of-service" target="_blank" rel="noreferrer">user terms</a>.</p></> },
    { id: "execution", title: "Orders, risk & settlement", body: <><p>Submitting a transaction does not guarantee an order is accepted or filled. Orders can be rejected, partially filled, cancelled, or left resting. Read the execution result and portfolio; a successful receipt alone is not proof of a completed trade.</p><p>The current configured market is fully backed at 1×. Interactive leverage examples are illustrations, not an offer of leverage in that market. Any future leveraged market would have its own disclosed limits, margin, liquidation, reserve, and settlement rules.</p><p>Price feeds, RPC endpoints, keepers, and automation can be delayed or unavailable. Stop-loss and other protection rules do not guarantee execution. Reserve liquidity can lose value and is subject to the displayed withdrawal restrictions. A finalized oracle outcome is not a claimable payout until contract preparation is complete.</p></> },
    { id: "availability", title: "Availability & changes", body: <p>The demo is offered as available, with no promise of uninterrupted access, accuracy, profitability, or preservation of testnet state. Software may contain defects; deployments, interfaces, and test networks may change or reset. Nothing here excludes rights or responsibilities that applicable law does not allow to be excluded.</p> },
    { id: "information", title: "Information & external services", body: <p>Website content and examples are educational product information, not personalized investment advice. External wallets, authentication providers, block explorers, and other linked services operate under their own terms. Review the <Link href="/privacy">privacy policy</Link> for information about data and browser storage.</p> },
    { id: "contact", title: "Questions & future versions", body: <><p>Contact the Eros Markets project team through the channel where you received access to the testnet for questions about these terms. Never share a private key or seed phrase.</p><p>The date above identifies this version. Material changes to the service or these terms will be reflected here. A future production release will require terms appropriate to its operator, features, and jurisdictions.</p></> },
  ]} />;
}
