// Generates typed `as const` ABIs from the repo's committed artifacts. Run: npm run gen:abis
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = join(root, "frontend", "src", "abi");
const sources = {
  engine: "oracle/out/RegistryBookRiskEngine.sol/RegistryBookRiskEngine.json",
  vault: "oracle/out/CollateralVault.sol/CollateralVault.json",
  resolutionOracle: "oracle/out/ResolutionOracle.sol/ResolutionOracle.json",
  marketRegistry: "oracle/out/MarketRegistry.sol/MarketRegistry.json",
  umaAdapter: "oracle/out/UmaAdapter.sol/UmaAdapter.json",
};

mkdirSync(out, { recursive: true });
for (const [name, path] of Object.entries(sources)) {
  const json = JSON.parse(readFileSync(join(root, path), "utf8"));
  const abi = Array.isArray(json) ? json : json.abi;
  const body = `// Generated by scripts/gen-abis.mjs from ${path}. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(out, `${name}.ts`), body);
  console.log(`${name}: ${abi.length} entries`);
}

// A stateless deployless lens compiled with the repository's pinned Solidity settings.
const lens = JSON.parse(readFileSync(join(root, "contracts/out/MarginLens.sol/MarginLens.json"), "utf8"));
writeFileSync(join(out, "marginLens.ts"), `// Generated from contracts/src/lens/MarginLens.sol by scripts/gen-abis.mjs.
export const marginLensAbi = ${JSON.stringify(lens.abi)} as const;
export const marginLensCode = ${JSON.stringify(lens.bytecode.object)} as const;
`);
