// Generates typed `as const` ABIs from the repo's committed artifacts. Run: npm run gen:abis
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = join(root, "frontend", "src", "abi");
const sources = {
  engine: "artifacts/risk/book-risk-engine-abi.json",
  vault: "artifacts/risk/vault-abi.json",
  resolutionOracle: "oracle/abi/ResolutionOracle.json",
  marketRegistry: "oracle/abi/MarketRegistry.json",
  umaAdapter: "oracle/abi/UmaAdapter.json",
};

mkdirSync(out, { recursive: true });
for (const [name, path] of Object.entries(sources)) {
  const json = JSON.parse(readFileSync(join(root, path), "utf8"));
  const abi = Array.isArray(json) ? json : json.abi;
  const body = `// Generated by scripts/gen-abis.mjs from ${path}. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(out, `${name}.ts`), body);
  console.log(`${name}: ${abi.length} entries`);
}
