// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

// GENERATED by reference/b/export_vectors.py (seed 20261001). Do not edit by hand.
// Expected values come from the independent Python reference (reference/b); tolerance T-1.

import {Test} from "forge-std/Test.sol";
import {MarginMath} from "../../../src/math/MarginMath.sol";
import {HazardMath} from "../../../src/math/HazardMath.sol";
import {PricingMath as PM} from "../../../src/math/PricingMath.sol";
import {LiquidationMath as LM} from "../../../src/math/LiquidationMath.sol";
import {LifecycleMath as LC} from "../../../src/math/LifecycleMath.sol";
import {OrderAdmissionMath as OA} from "../../../src/math/OrderAdmissionMath.sol";
import {RiskFixture} from "./B011.t.sol";

abstract contract RiskDifferential is Test {
    uint256 internal constant QD = 1e18;
    uint256 internal constant UD = 1000 * QD;

    function _upper(uint256 sol, uint256 refHi, string memory what) internal pure {
        assertGe(sol, refHi, what);
        uint256 tol = refHi / 1e12 > 1e3 ? refHi / 1e12 : 1e3;
        assertLe(sol - refHi, tol, what);
    }

    function _m(uint256 n, bool isLong, uint256 q, uint256 s, uint256 mm, uint256 im, bool full)
        internal
        pure
    {
        MarginMath.Margin memory r = MarginMath.sideMargin(n, isLong, q, s, 0, RiskFixture.profile(5, true));
        if (full) {
            assertTrue(r.fullBacking, "reference full backing");
            assertEq(r.imQ, im, "full-backing IM = worst loss");
        } else {
            _upper(r.mmQ, mm, "MM");
            _upper(r.imQ, im, "IM");
        }
    }

    function test_diffMargin() public pure {
        _m(1000, false, 300000000000000000, 86400, 273709452386153202789940, 410564178579229804184910, false);
        _m(
            1099511627776,
            false,
            999000000000000000,
            604800,
            1099511627776000000000000000000,
            1099511627776000000000000000000,
            true
        );
        _m(7, true, 950000000000000000, 3600, 4417073700797964902080, 6625610551196947353120, false);
        _m(7, true, 999000000000000000, 3600, 670500096428665743548, 1398600000000000000000, false);
        _m(999, true, 600000000000000000, 604800, 113461822863386235084945, 170192734295079352627417, false);
        _m(1000, true, 950000000000000000, 86400, 132797065910654077369117, 199195598865981116053676, false);
        _m(
            1000000,
            true,
            50000000000000000,
            86400,
            50000000000000000000000000,
            50000000000000000000000000,
            true
        );
        _m(1000, false, 950000000000000000, 3600, 50000000000000000000000, 50000000000000000000000, true);
        _m(
            3333333,
            true,
            600000000000000000,
            3600,
            1999999800000000000000000000,
            1999999800000000000000000000,
            true
        );
        _m(
            100000000,
            true,
            999000000000000000,
            1,
            99900000000000000000000000000,
            99900000000000000000000000000,
            true
        );
        _m(
            1099511627776,
            true,
            999000000000000000,
            604800,
            1098412116148224000000000000000000,
            1098412116148224000000000000000000,
            true
        );
        _m(
            3333333,
            true,
            600000000000000000,
            3600,
            1999999800000000000000000000,
            1999999800000000000000000000,
            true
        );
        _m(999, true, 999000000000000000, 2505600, 8433623141528976345638, 199600200000000000000000, false);
        _m(
            3333333,
            false,
            600000000000000000,
            1,
            1333333200000000000000000000,
            1333333200000000000000000000,
            true
        );
        _m(
            1099511627776,
            false,
            50000000000000000,
            604800,
            1044536046387200000000000000000000,
            1044536046387200000000000000000000,
            true
        );
        _m(
            1099511627776,
            true,
            950000000000000000,
            604800,
            1044536046387200000000000000000000,
            1044536046387200000000000000000000,
            true
        );
        _m(
            12345,
            true,
            950000000000000000,
            3600,
            7799430506198277401358774,
            11699145759297416102038161,
            false
        );
        _m(1000, true, 50000000000000000, 3600, 50000000000000000000000, 50000000000000000000000, true);
        _m(
            250000,
            false,
            50000000000000000,
            604800,
            13653875661191181377924039,
            47500000000000000000000000,
            false
        );
        _m(
            250000,
            false,
            300000000000000000,
            2505600,
            14062564052551892613285722,
            35000000000000000000000000,
            false
        );
        _m(7, false, 50000000000000000, 604800, 373084460668678831493, 1330000000000000000000, false);
        _m(
            3333333,
            true,
            600000000000000000,
            2505600,
            251755186167722889716160100,
            399999960000000000000000000,
            false
        );
        _m(
            12345,
            true,
            950000000000000000,
            2505600,
            355095488187640505498336,
            2345550000000000000000000,
            false
        );
        _m(
            250000,
            true,
            600000000000000000,
            1,
            150000000000000000000000000,
            150000000000000000000000000,
            true
        );
        _m(1000, true, 50000000000000000, 2505600, 28732053227432888054309, 43098079841149332081463, false);
        _m(
            1000000,
            true,
            600000000000000000,
            3600,
            600000000000000000000000000,
            600000000000000000000000000,
            true
        );
        _m(999, false, 600000000000000000, 2505600, 58285543536728777068346, 87428315305093165602519, false);
        _m(1000, false, 50000000000000000, 3600, 631073187017921826660467, 946609780526882739990701, false);
        _m(
            250000,
            false,
            950000000000000000,
            2505600,
            7360050923135505894612068,
            11040076384703258841918102,
            false
        );
        _m(1000, false, 950000000000000000, 3600, 50000000000000000000000, 50000000000000000000000, true);
        _m(999, true, 1000000000000000, 604800, 999000000000000000000, 999000000000000000000, true);
        _m(999, false, 999000000000000000, 3600, 999000000000000000000, 999000000000000000000, true);
        _m(
            1099511627776,
            false,
            50000000000000000,
            2505600,
            1044536046387200000000000000000000,
            1044536046387200000000000000000000,
            true
        );
        _m(
            1000000,
            false,
            300000000000000000,
            1,
            700000000000000000000000000,
            700000000000000000000000000,
            true
        );
        _m(1000, false, 50000000000000000, 1, 950000000000000000000000, 950000000000000000000000, true);
        _m(
            1000000,
            false,
            1000000000000000,
            3600,
            104951054230445316956834981,
            199800000000000000000000000,
            false
        );
        _m(
            1099511627776,
            false,
            950000000000000000,
            3600,
            54975581388800000000000000000000,
            54975581388800000000000000000000,
            true
        );
        _m(
            3333333,
            false,
            50000000000000000,
            2505600,
            124336199588103866383749012,
            633333270000000000000000000,
            false
        );
        _m(
            3333333,
            false,
            1000000000000000,
            2505600,
            37031050885905075688195711,
            665999933400000000000000000,
            false
        );
        _m(
            250000,
            true,
            600000000000000000,
            86400,
            74862941066638476370390174,
            112294411599957714555585261,
            false
        );
        _m(
            1000000,
            false,
            50000000000000000,
            86400,
            145480613917779167723154464,
            218220920876668751584731696,
            false
        );
        _m(1000, false, 300000000000000000, 1, 700000000000000000000000, 700000000000000000000000, true);
        _m(
            250000,
            false,
            50000000000000000,
            604800,
            13653875661191181377924039,
            47500000000000000000000000,
            false
        );
        _m(7, false, 999000000000000000, 604800, 7000000000000000000, 7000000000000000000, true);
        _m(999, true, 950000000000000000, 86400, 132664255580473671534941, 198996383370710507302411, false);
        _m(999, true, 50000000000000000, 86400, 49950000000000000000000, 49950000000000000000000, true);
        _m(999, false, 1000000000000000, 604800, 11993459881772039536892, 199600200000000000000000, false);
        _m(999, true, 1000000000000000, 2505600, 999000000000000000000, 999000000000000000000, true);
        _m(12345, true, 600000000000000000, 3600, 7407000000000000000000000, 7407000000000000000000000, true);
        _m(
            1099511627776,
            false,
            999000000000000000,
            604800,
            1099511627776000000000000000000,
            1099511627776000000000000000000,
            true
        );
        _m(999, false, 50000000000000000, 86400, 132664255580473671534941, 198996383370710507302411, false);
        _m(
            1000000,
            true,
            1000000000000000,
            2505600,
            1000000000000000000000000,
            1000000000000000000000000,
            true
        );
        _m(12345, false, 600000000000000000, 1, 4938000000000000000000000, 4938000000000000000000000, true);
        _m(1000, true, 50000000000000000, 3600, 50000000000000000000000, 50000000000000000000000, true);
        _m(
            12345,
            true,
            999000000000000000,
            604800,
            148375547149040504606444,
            2466531000000000000000000,
            false
        );
        _m(1, true, 600000000000000000, 2505600, 58337995901789254987, 120000000000000000000, false);
        _m(
            1099511627776,
            false,
            50000000000000000,
            1,
            1044536046387200000000000000000000,
            1044536046387200000000000000000000,
            true
        );
        _m(999, true, 1000000000000000, 604800, 999000000000000000000, 999000000000000000000, true);
        _m(1000, true, 999000000000000000, 2505600, 8442066050835501801728, 199800000000000000000000, false);
        _m(
            100000000,
            false,
            950000000000000000,
            3600,
            5000000000000000000000000000,
            5000000000000000000000000000,
            true
        );
        _m(1000, false, 1000000000000000, 86400, 23533898855455969475388, 199800000000000000000000, false);
        _m(
            3333333,
            false,
            1000000000000000,
            3600,
            412905976275009443231934654,
            665999933400000000000000000,
            false
        );
        _m(
            250000,
            true,
            50000000000000000,
            604800,
            12500000000000000000000000,
            12500000000000000000000000,
            true
        );
        _m(1000, true, 300000000000000000, 86400, 273709591302916358725015, 300000000000000000000000, true);
        _m(
            3333333,
            true,
            300000000000000000,
            1,
            999999900000000000000000000,
            999999900000000000000000000,
            true
        );
        _m(
            250000,
            false,
            999000000000000000,
            604800,
            250000000000000000000000,
            250000000000000000000000,
            true
        );
        _m(
            250000,
            false,
            600000000000000000,
            3600,
            100000000000000000000000000,
            100000000000000000000000000,
            true
        );
        _m(12345, false, 999000000000000000, 86400, 12345000000000000000000, 12345000000000000000000, true);
        _m(
            3333333,
            false,
            1000000000000000,
            1,
            3329999667000000000000000000,
            3329999667000000000000000000,
            true
        );
        _m(
            3333333,
            false,
            950000000000000000,
            2505600,
            124337935700981311770324095,
            166666650000000000000000000,
            true
        );
        _m(
            3333333,
            false,
            50000000000000000,
            2505600,
            124336199588103866383749012,
            633333270000000000000000000,
            false
        );
        _m(
            1099511627776,
            true,
            950000000000000000,
            86400,
            1044536046387200000000000000000000,
            1044536046387200000000000000000000,
            true
        );
        _m(
            3333333,
            false,
            1000000000000000,
            1,
            3329999667000000000000000000,
            3329999667000000000000000000,
            true
        );
        _m(
            100000000,
            false,
            999000000000000000,
            1,
            100000000000000000000000000,
            100000000000000000000000000,
            true
        );
        _m(999, true, 1000000000000000, 86400, 999000000000000000000, 999000000000000000000, true);
        _m(
            250000,
            false,
            300000000000000000,
            2505600,
            14062564052551892613285722,
            35000000000000000000000000,
            false
        );
        _m(
            100000000,
            true,
            50000000000000000,
            86400,
            5000000000000000000000000000,
            5000000000000000000000000000,
            true
        );
        _m(
            1000000,
            false,
            300000000000000000,
            3600,
            700000000000000000000000000,
            700000000000000000000000000,
            true
        );
        _m(
            3333333,
            true,
            50000000000000000,
            3600,
            166666650000000000000000000,
            166666650000000000000000000,
            true
        );
        _m(
            250000,
            true,
            950000000000000000,
            3600,
            161648752825295061519460661,
            237500000000000000000000000,
            true
        );
        _m(
            250000,
            false,
            999000000000000000,
            2505600,
            250000000000000000000000,
            250000000000000000000000,
            true
        );
        _m(1, false, 999000000000000000, 86400, 1000000000000000000, 1000000000000000000, true);
        _m(
            1099511627776,
            true,
            950000000000000000,
            86400,
            1044536046387200000000000000000000,
            1044536046387200000000000000000000,
            true
        );
        _m(
            3333333,
            true,
            300000000000000000,
            86400,
            999999900000000000000000000,
            999999900000000000000000000,
            true
        );
        _m(999, false, 300000000000000000, 86400, 273435715594666573501451, 410153573391999860252176, false);
        _m(
            3333333,
            true,
            999000000000000000,
            3600,
            412905976275009443231934654,
            665999933400000000000000000,
            false
        );
        _m(12345, true, 50000000000000000, 604800, 617250000000000000000000, 617250000000000000000000, true);
        _m(7, false, 950000000000000000, 604800, 350000000000000000000, 350000000000000000000, true);
        _m(
            250000,
            false,
            50000000000000000,
            86400,
            34016133064233760952369373,
            51024199596350641428554060,
            false
        );
        _m(1, true, 600000000000000000, 86400, 292233287169605076164, 438349930754407614245, false);
        _m(
            1000000,
            true,
            600000000000000000,
            2505600,
            63929058071268787211717393,
            120000000000000000000000000,
            false
        );
        _m(
            1000000,
            false,
            600000000000000000,
            2505600,
            63929141404671565047365589,
            95893712107007347571048384,
            false
        );
    }

    function test_diffTail() public pure {
        HazardMath.Tail memory t;
        t = HazardMath.tail(155746411517096, 11465687486007000, false, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(2649407464663695, 607142569030278, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 11605301366312475777, "k");
        t = HazardMath.tail(1934591184215277, 7913004611240580, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 11079098014370027894, "k");
        t = HazardMath.tail(10896554473363180, 2567303580885420, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 11541025480550108423, "k");
        t = HazardMath.tail(354446469611696, 4071114238501711, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 10131039753497269572, "k");
        t = HazardMath.tail(9547748410106610, 5781513290091426, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 15319311766878136262, "k");
        t = HazardMath.tail(5944660191780553, 4038324036545856, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 15624422417080435752, "k");
        t = HazardMath.tail(10432439668558146, 9005363157765311, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(1409130354134808, 2392817046472384, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 11407898979060344694, "k");
        t = HazardMath.tail(9490577351616643, 6177210384756745, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 16092643798110709775, "k");
        t = HazardMath.tail(686618854190470, 9347560732113976, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 38953595614141030911, "k");
        t = HazardMath.tail(7795896836225428, 925611954847297, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 10445011532724628245, "k");
        t = HazardMath.tail(6834821862087641, 3150828740247109, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 17685547890678906742, "k");
        t = HazardMath.tail(300055966403650, 10352293380195252, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 10102595930902589923, "k");
        t = HazardMath.tail(4629258612573920, 7830901305470901, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 13576895552051403855, "k");
        t = HazardMath.tail(452839807789888, 6576356919578457, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 17004871560830145024, "k");
        t = HazardMath.tail(6263090753968502, 3633695172682609, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 12470213316020014187, "k");
        t = HazardMath.tail(1346728278829552, 8513974501869820, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 25810978354542020606, "k");
        t = HazardMath.tail(11202637166407732, 1563957228687024, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 10832986721480598444, "k");
        t = HazardMath.tail(6711063894589723, 1905990112232123, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 17349616483160353601, "k");
        t = HazardMath.tail(10664569965064611, 6174384883912782, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(1691592984229871, 9562449439258924, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 10915879061203840532, "k");
        t = HazardMath.tail(10495580621586561, 9651904718979559, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(1014434945322032, 3620409881737375, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 12457222140276091867, "k");
        t = HazardMath.tail(11048267630944586, 10354524993044566, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(2627307983731031, 9639087728386199, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 11587894995890454232, "k");
        t = HazardMath.tail(11182015883805509, 4081707643816897, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(7469764742000772, 5705719816982728, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 19780494555352217482, "k");
        t = HazardMath.tail(10456185328217290, 5287771294840510, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(11858252847710458, 10000439824216962, false, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(2808348197453498, 8934649526802744, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 30483957378536407572, "k");
        t = HazardMath.tail(11951909926829443, 7595613532696564, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(8377422261637858, 9709730360040821, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 24701017348600803466, "k");
        t = HazardMath.tail(8711073937412956, 3875381031585813, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 12713878587238582661, "k");
        t = HazardMath.tail(6286518418024101, 577525586502365, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 16327773236241970503, "k");
        t = HazardMath.tail(4698390762081099, 10799062827619091, true, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 13665129135548034637, "k");
        t = HazardMath.tail(810370233528500, 67696771476355, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 9983725055583605840, "k");
        t = HazardMath.tail(1029060526172422, 4983240119745432, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 14047723160248036741, "k");
        t = HazardMath.tail(10777534690059873, 7584585236240931, true, 1e16);
        assertTrue(t.fullBacking);
        t = HazardMath.tail(4518062875923755, 944593598129617, false, 1e16);
        assertFalse(t.fullBacking);
        _upper(t.kWad, 10455953045706661404, "k");
    }

    function test_diffTwap() public pure {
        PM.Sample[] memory x;
        PM.Twap memory r;
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10031, 340928195846529784, false);
        x[1] = PM.Sample(10032, 243633249129739901, true);
        r = PM.twap(x, 10062, 300, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 30);
        x = new PM.Sample[](12);
        x[0] = PM.Sample(10001, 812873254535581051, true);
        x[1] = PM.Sample(10032, 487950571205287478, true);
        x[2] = PM.Sample(10077, 118484020379792954, true);
        x[3] = PM.Sample(10078, 253299697445478366, true);
        x[4] = PM.Sample(10079, 432182807373451364, true);
        x[5] = PM.Sample(10080, 656223583704292486, true);
        x[6] = PM.Sample(10097, 922003323626926493, true);
        x[7] = PM.Sample(10128, 3467760697564960, true);
        x[8] = PM.Sample(10173, 122346580901670322, true);
        x[9] = PM.Sample(10218, 166879472940631322, true);
        x[10] = PM.Sample(10263, 398786659657527201, true);
        x[11] = PM.Sample(10264, 963749118312831675, false);
        r = PM.twap(x, 10295, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 14);
        x = new PM.Sample[](10);
        x[0] = PM.Sample(10045, 461629231448193574, true);
        x[1] = PM.Sample(10075, 437564751474941869, true);
        x[2] = PM.Sample(10120, 356475859162061503, false);
        x[3] = PM.Sample(10150, 107429368779970014, true);
        x[4] = PM.Sample(10179, 46509457298673096, true);
        x[5] = PM.Sample(10224, 127917320668955167, true);
        x[6] = PM.Sample(10241, 485875219862075069, true);
        x[7] = PM.Sample(10242, 739218579030729630, true);
        x[8] = PM.Sample(10272, 211887012051118674, true);
        x[9] = PM.Sample(10302, 587513171217076785, true);
        r = PM.twap(x, 10302, 30, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 30);
        assertEq(r.twapWad, 211887012051118674);
        x = new PM.Sample[](7);
        x[0] = PM.Sample(10031, 653306804080132576, true);
        x[1] = PM.Sample(10076, 193749017557685092, false);
        x[2] = PM.Sample(10106, 237822176359718214, true);
        x[3] = PM.Sample(10107, 331520660073735969, true);
        x[4] = PM.Sample(10152, 433066101621780601, true);
        x[5] = PM.Sample(10152, 987754177806843927, false);
        x[6] = PM.Sample(10169, 506823946416540355, true);
        r = PM.twap(x, 10169, 1, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 0);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10001, 709492697256142513, true);
        x[1] = PM.Sample(10046, 790376320299916943, true);
        r = PM.twap(x, 10077, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 44);
        x = new PM.Sample[](4);
        x[0] = PM.Sample(10045, 169927678055279009, true);
        x[1] = PM.Sample(10045, 41898270329814259, true);
        x[2] = PM.Sample(10074, 749788044150967095, false);
        x[3] = PM.Sample(10075, 229378570705502462, true);
        r = PM.twap(x, 10106, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](8);
        x[0] = PM.Sample(10001, 78393680362270181, true);
        x[1] = PM.Sample(10006, 563043896736542866, true);
        x[2] = PM.Sample(10006, 421284365677087293, true);
        x[3] = PM.Sample(10006, 698926692899374573, true);
        x[4] = PM.Sample(10036, 963017090609080651, true);
        x[5] = PM.Sample(10053, 28635112951399753, true);
        x[6] = PM.Sample(10098, 717863101705377344, true);
        x[7] = PM.Sample(10098, 518542906398067012, true);
        r = PM.twap(x, 10098, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 75);
        x = new PM.Sample[](11);
        x[0] = PM.Sample(10029, 53104415008410621, true);
        x[1] = PM.Sample(10034, 561330762087358178, true);
        x[2] = PM.Sample(10035, 470795088536898264, true);
        x[3] = PM.Sample(10066, 974225456549786040, true);
        x[4] = PM.Sample(10066, 131993716563328847, true);
        x[5] = PM.Sample(10111, 431613030513249552, false);
        x[6] = PM.Sample(10116, 844046646853055040, true);
        x[7] = PM.Sample(10133, 312125797897976675, true);
        x[8] = PM.Sample(10150, 759878832954683999, false);
        x[9] = PM.Sample(10181, 401016482166491400, true);
        x[10] = PM.Sample(10226, 2757370205690576, true);
        r = PM.twap(x, 10256, 300, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 160);
        x = new PM.Sample[](8);
        x[0] = PM.Sample(10031, 636115473167100735, true);
        x[1] = PM.Sample(10076, 260101350197404249, true);
        x[2] = PM.Sample(10105, 91974811594002019, true);
        x[3] = PM.Sample(10122, 178340315996805271, true);
        x[4] = PM.Sample(10139, 782924879470142592, false);
        x[5] = PM.Sample(10139, 600537117101662101, true);
        x[6] = PM.Sample(10144, 491644672744155886, true);
        x[7] = PM.Sample(10189, 432302596060609985, true);
        r = PM.twap(x, 10189, 300, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 128);
        x = new PM.Sample[](7);
        x[0] = PM.Sample(10031, 858705121503975566, true);
        x[1] = PM.Sample(10060, 692017487973099506, false);
        x[2] = PM.Sample(10061, 455391408595193340, true);
        x[3] = PM.Sample(10078, 480587569607134156, true);
        x[4] = PM.Sample(10095, 356504797666080482, true);
        x[5] = PM.Sample(10096, 545215682552555105, true);
        x[6] = PM.Sample(10113, 659278314862828132, true);
        r = PM.twap(x, 10116, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](11);
        x[0] = PM.Sample(10017, 553739571048697518, false);
        x[1] = PM.Sample(10046, 171874336866486396, true);
        x[2] = PM.Sample(10075, 710277329092661358, true);
        x[3] = PM.Sample(10105, 425103622276892105, true);
        x[4] = PM.Sample(10106, 115092259177432099, true);
        x[5] = PM.Sample(10151, 641082616525225301, true);
        x[6] = PM.Sample(10180, 56665312117151563, true);
        x[7] = PM.Sample(10211, 872849404167921575, true);
        x[8] = PM.Sample(10228, 803899834402352738, true);
        x[9] = PM.Sample(10233, 356924143434305674, true);
        x[10] = PM.Sample(10234, 591071871111384273, true);
        r = PM.twap(x, 10264, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](1);
        x[0] = PM.Sample(10030, 585634072092148061, true);
        r = PM.twap(x, 10033, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 585634072092148061);
        x = new PM.Sample[](10);
        x[0] = PM.Sample(10000, 83320146058749343, true);
        x[1] = PM.Sample(10030, 267756458381921668, true);
        x[2] = PM.Sample(10030, 686103200480888183, true);
        x[3] = PM.Sample(10059, 762010393731334019, true);
        x[4] = PM.Sample(10059, 90072853288831443, true);
        x[5] = PM.Sample(10104, 561366866963891849, true);
        x[6] = PM.Sample(10121, 45704024935112208, true);
        x[7] = PM.Sample(10152, 986118132141303741, true);
        x[8] = PM.Sample(10197, 377290303291711958, true);
        x[9] = PM.Sample(10228, 691362446012805394, true);
        r = PM.twap(x, 10258, 10, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 10);
        assertEq(r.twapWad, 691362446012805394);
        x = new PM.Sample[](11);
        x[0] = PM.Sample(10045, 541597475925906613, true);
        x[1] = PM.Sample(10090, 925116467149280482, false);
        x[2] = PM.Sample(10120, 613021130143001573, true);
        x[3] = PM.Sample(10165, 122475805621784525, true);
        x[4] = PM.Sample(10196, 508431869951923208, true);
        x[5] = PM.Sample(10225, 584840638629923142, true);
        x[6] = PM.Sample(10270, 14120734903899737, false);
        x[7] = PM.Sample(10287, 559834469546854078, false);
        x[8] = PM.Sample(10318, 967738174193058301, true);
        x[9] = PM.Sample(10349, 971988770228244168, true);
        x[10] = PM.Sample(10379, 774002535057335476, true);
        r = PM.twap(x, 10382, 30, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 30);
        assertEq(r.twapWad, 952190146711153298);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10000, 591469416676654362, true);
        x[1] = PM.Sample(10031, 417483333726886022, true);
        r = PM.twap(x, 10062, 10, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 9);
        x = new PM.Sample[](11);
        x[0] = PM.Sample(10001, 747450042490745132, true);
        x[1] = PM.Sample(10006, 793633848297579385, true);
        x[2] = PM.Sample(10006, 748633007972277670, true);
        x[3] = PM.Sample(10023, 964072057727583999, true);
        x[4] = PM.Sample(10023, 238618405387610679, true);
        x[5] = PM.Sample(10028, 984241311799983672, true);
        x[6] = PM.Sample(10058, 104145188017464599, true);
        x[7] = PM.Sample(10075, 150704903642649088, true);
        x[8] = PM.Sample(10092, 188881408518034294, true);
        x[9] = PM.Sample(10121, 63499345320797560, true);
        x[10] = PM.Sample(10152, 528814690980979841, false);
        r = PM.twap(x, 10152, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](7);
        x[0] = PM.Sample(10005, 836909542324592731, true);
        x[1] = PM.Sample(10035, 855849115884333697, true);
        x[2] = PM.Sample(10080, 716194286210021598, false);
        x[3] = PM.Sample(10097, 950953775075244017, true);
        x[4] = PM.Sample(10114, 820399923357663228, true);
        x[5] = PM.Sample(10114, 868452405633900068, true);
        x[6] = PM.Sample(10119, 414550671140930171, true);
        r = PM.twap(x, 10119, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 868452405633900068);
        x = new PM.Sample[](8);
        x[0] = PM.Sample(10000, 170997154941931410, false);
        x[1] = PM.Sample(10029, 772758580797068779, true);
        x[2] = PM.Sample(10034, 287217473189011730, false);
        x[3] = PM.Sample(10051, 24165239616546579, false);
        x[4] = PM.Sample(10081, 693692212380288409, false);
        x[5] = PM.Sample(10111, 539187316899901493, true);
        x[6] = PM.Sample(10141, 499828263237237932, false);
        x[7] = PM.Sample(10142, 313209972072477047, true);
        r = PM.twap(x, 10173, 30, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 29);
        x = new PM.Sample[](5);
        x[0] = PM.Sample(10000, 572739639162932515, false);
        x[1] = PM.Sample(10005, 768969887076389163, true);
        x[2] = PM.Sample(10050, 723586531081622935, true);
        x[3] = PM.Sample(10079, 390483320217910712, false);
        x[4] = PM.Sample(10084, 237761218641403998, true);
        r = PM.twap(x, 10084, 300, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](4);
        x[0] = PM.Sample(10001, 957877330727599784, true);
        x[1] = PM.Sample(10001, 34297239219186949, true);
        x[2] = PM.Sample(10018, 160009011105434, true);
        x[3] = PM.Sample(10023, 959704612888039621, true);
        r = PM.twap(x, 10026, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 959704612888039621);
        x = new PM.Sample[](3);
        x[0] = PM.Sample(10029, 805580577772912540, true);
        x[1] = PM.Sample(10058, 354253900799430466, true);
        x[2] = PM.Sample(10075, 197858535846379445, true);
        r = PM.twap(x, 10106, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](3);
        x[0] = PM.Sample(10005, 781478843612737500, false);
        x[1] = PM.Sample(10010, 659468210732441920, true);
        x[2] = PM.Sample(10027, 455201561816657035, true);
        r = PM.twap(x, 10057, 10, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 10);
        assertEq(r.twapWad, 455201561816657035);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10000, 208235713947813172, true);
        x[1] = PM.Sample(10001, 839448145352114872, true);
        r = PM.twap(x, 10031, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 839448145352114872);
        x = new PM.Sample[](13);
        x[0] = PM.Sample(10000, 3787933117721976, true);
        x[1] = PM.Sample(10005, 761031116802482725, true);
        x[2] = PM.Sample(10035, 612428853713702505, true);
        x[3] = PM.Sample(10052, 49429501976140878, true);
        x[4] = PM.Sample(10097, 419059083724503351, true);
        x[5] = PM.Sample(10126, 718939103791759646, true);
        x[6] = PM.Sample(10131, 512504194451331241, true);
        x[7] = PM.Sample(10131, 900644264960500882, true);
        x[8] = PM.Sample(10148, 268363842914268222, true);
        x[9] = PM.Sample(10153, 593535195782767452, true);
        x[10] = PM.Sample(10158, 154299477917900641, true);
        x[11] = PM.Sample(10158, 743342228696427282, true);
        x[12] = PM.Sample(10175, 159348666644948351, true);
        r = PM.twap(x, 10175, 30, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 30);
        assertEq(r.twapWad, 654941529206864827);
        x = new PM.Sample[](6);
        x[0] = PM.Sample(10005, 178228615328169611, true);
        x[1] = PM.Sample(10035, 834224823330963719, true);
        x[2] = PM.Sample(10064, 78895772618447074, true);
        x[3] = PM.Sample(10065, 340411534939748392, true);
        x[4] = PM.Sample(10082, 24539889840384518, true);
        x[5] = PM.Sample(10087, 585411205820556870, true);
        r = PM.twap(x, 10117, 90, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 90);
        assertEq(r.twapWad, 546325292107067812);
        x = new PM.Sample[](10);
        x[0] = PM.Sample(10005, 76518513168786083, false);
        x[1] = PM.Sample(10010, 119289396269794801, true);
        x[2] = PM.Sample(10055, 166683489848443871, true);
        x[3] = PM.Sample(10060, 718440377589281164, true);
        x[4] = PM.Sample(10105, 532221652251950676, false);
        x[5] = PM.Sample(10150, 249293555909981765, false);
        x[6] = PM.Sample(10179, 425554498310829723, true);
        x[7] = PM.Sample(10208, 473524748466981810, true);
        x[8] = PM.Sample(10253, 39734348972626830, true);
        x[9] = PM.Sample(10284, 146004355785675646, true);
        r = PM.twap(x, 10284, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 74);
        x = new PM.Sample[](1);
        x[0] = PM.Sample(10029, 845946562555011155, true);
        r = PM.twap(x, 10059, 30, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 30);
        assertEq(r.twapWad, 845946562555011155);
        x = new PM.Sample[](7);
        x[0] = PM.Sample(10005, 750556139501142732, true);
        x[1] = PM.Sample(10034, 895804363819110425, true);
        x[2] = PM.Sample(10079, 600774408883732652, true);
        x[3] = PM.Sample(10108, 497426724428051273, true);
        x[4] = PM.Sample(10108, 144350827086638726, true);
        x[5] = PM.Sample(10138, 78552792345869430, true);
        x[6] = PM.Sample(10138, 417982060061161821, true);
        r = PM.twap(x, 10138, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 144350827086638726);
        x = new PM.Sample[](13);
        x[0] = PM.Sample(10030, 868843518171464990, true);
        x[1] = PM.Sample(10059, 380053446485536892, true);
        x[2] = PM.Sample(10089, 856221149728693522, true);
        x[3] = PM.Sample(10106, 573236312128673647, true);
        x[4] = PM.Sample(10136, 857969286979267274, true);
        x[5] = PM.Sample(10136, 757019111506295812, true);
        x[6] = PM.Sample(10141, 783327486393468837, false);
        x[7] = PM.Sample(10172, 322744777207041475, true);
        x[8] = PM.Sample(10203, 775418062421570568, true);
        x[9] = PM.Sample(10232, 179134471882802271, true);
        x[10] = PM.Sample(10232, 422687536334265574, true);
        x[11] = PM.Sample(10232, 504833822401350699, true);
        x[12] = PM.Sample(10237, 869570958416252550, true);
        r = PM.twap(x, 10267, 10, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 10);
        assertEq(r.twapWad, 869570958416252550);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10000, 163463748128562404, true);
        x[1] = PM.Sample(10005, 692152176762773833, true);
        r = PM.twap(x, 10008, 10, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 8);
        x = new PM.Sample[](11);
        x[0] = PM.Sample(10030, 643958649357066115, true);
        x[1] = PM.Sample(10030, 423057126936450154, true);
        x[2] = PM.Sample(10060, 986514890850460540, true);
        x[3] = PM.Sample(10090, 612549154944491483, true);
        x[4] = PM.Sample(10119, 129397528782945901, false);
        x[5] = PM.Sample(10150, 27405121002868535, true);
        x[6] = PM.Sample(10179, 863100379936712894, true);
        x[7] = PM.Sample(10224, 773802945698279704, true);
        x[8] = PM.Sample(10225, 396934421948241003, true);
        x[9] = PM.Sample(10254, 947660872021514929, true);
        x[10] = PM.Sample(10259, 986723673619467647, false);
        r = PM.twap(x, 10289, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 45);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10031, 672284020812559220, true);
        x[1] = PM.Sample(10036, 285445855445196433, true);
        r = PM.twap(x, 10066, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 285445855445196433);
        x = new PM.Sample[](0);
        r = PM.twap(x, 10030, 300, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 0);
        x = new PM.Sample[](4);
        x[0] = PM.Sample(10031, 600236897307844130, true);
        x[1] = PM.Sample(10076, 273677710723303360, true);
        x[2] = PM.Sample(10121, 682875934463496221, true);
        x[3] = PM.Sample(10152, 476781742312951811, true);
        r = PM.twap(x, 10183, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 73);
        x = new PM.Sample[](10);
        x[0] = PM.Sample(10029, 944875238191512042, true);
        x[1] = PM.Sample(10030, 455690452829963998, true);
        x[2] = PM.Sample(10061, 594553327672370150, false);
        x[3] = PM.Sample(10078, 964209681371909211, true);
        x[4] = PM.Sample(10107, 545248751344082638, true);
        x[5] = PM.Sample(10136, 998465304374331790, true);
        x[6] = PM.Sample(10137, 447617281008194547, true);
        x[7] = PM.Sample(10142, 265912551891416632, true);
        x[8] = PM.Sample(10171, 962549242500104341, true);
        x[9] = PM.Sample(10200, 935376154387918215, true);
        r = PM.twap(x, 10230, 90, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 90);
        assertEq(r.twapWad, 717576791455644930);
        x = new PM.Sample[](3);
        x[0] = PM.Sample(10031, 351610919310597151, true);
        x[1] = PM.Sample(10031, 446652394992629030, true);
        x[2] = PM.Sample(10060, 712481679138333736, true);
        r = PM.twap(x, 10091, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 59);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10030, 23079304796428525, false);
        x[1] = PM.Sample(10035, 247909242117064581, true);
        r = PM.twap(x, 10035, 10, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 0);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10031, 513389610633117568, true);
        x[1] = PM.Sample(10061, 925790755512376613, true);
        r = PM.twap(x, 10091, 1, 30);
        assertEq(r.available, true);
        assertEq(r.coveredSecs, 1);
        assertEq(r.twapWad, 925790755512376613);
        x = new PM.Sample[](8);
        x[0] = PM.Sample(10005, 322998528395682218, true);
        x[1] = PM.Sample(10006, 766668609501919853, true);
        x[2] = PM.Sample(10023, 459972444883996757, true);
        x[3] = PM.Sample(10068, 850498962527586148, true);
        x[4] = PM.Sample(10098, 54327349178043457, true);
        x[5] = PM.Sample(10143, 154499285961668490, true);
        x[6] = PM.Sample(10172, 326119955605945508, true);
        x[7] = PM.Sample(10172, 939416601916333866, false);
        r = PM.twap(x, 10203, 60, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 29);
        x = new PM.Sample[](2);
        x[0] = PM.Sample(10000, 569265422205604731, false);
        x[1] = PM.Sample(10000, 621151882745291936, false);
        r = PM.twap(x, 10000, 90, 30);
        assertEq(r.available, false);
        assertEq(r.coveredSecs, 0);
    }

    function test_diffEstimate() public pure {
        uint256 lots;
        bool full;
        (lots, full) =
            LM.sizeEstimateLots(90233272422060446448529426, 19298785715917462800208430, 1000000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 836343);
        assertLe(lots, 836343 + 1);
        (lots, full) =
            LM.sizeEstimateLots(90233272422060446448529426, 41171695096051290978974058, 1000000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 577573);
        assertLe(lots, 577573 + 1);
        (lots, full) =
            LM.sizeEstimateLots(4137531734914865962794177, 2069190734225283292181334, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 26607);
        assertLe(lots, 26607 + 1);
        (lots, full) =
            LM.sizeEstimateLots(1075623095973123247168418070, 3609822671660443079126205, 7654321, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 7654321);
        assertLe(lots, 7654321 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1012702246779089621969152549, 829226641700708376732427522, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 1449485);
        assertLe(lots, 1449485 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1075623095973123247168418070, 573771782686104223470916145, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 3755039);
        assertLe(lots, 3755039 + 1);
        (lots, full) = LM.sizeEstimateLots(82348085312605626802933, 30582118755918238016286, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 670);
        assertLe(lots, 670 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1012702246779089621969152549, 730201777836110001024647713, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 2238776);
        assertLe(lots, 2238776 + 1);
        (lots, full) =
            LM.sizeEstimateLots(4137531734914865962794177, 2512667325443552831659803, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 20902);
        assertLe(lots, 20902 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1012702246779089621969152549, 477218492670180107830647221, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 4278205);
        assertLe(lots, 4278205 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 106809433701008424427646, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 115);
        assertLe(lots, 115 + 1);
        (lots, full) =
            LM.sizeEstimateLots(90233272422060446448529426, 37649527965983206776289362, 1000000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 619189);
        assertLe(lots, 619189 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 23927137050529510596931, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 836);
        assertLe(lots, 836 + 1);
        (lots, full) = LM.sizeEstimateLots(82348085312605626802933, 1389099137640694179666, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 1000);
        assertLe(lots, 1000 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1012702246779089621969152549, 286898296349865805153634735, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 5835041);
        assertLe(lots, 5835041 + 1);
        (lots, full) =
            LM.sizeEstimateLots(6000000000000000000000000, 1358222729728094020728796, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 40371);
        assertLe(lots, 40371 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 108867587108048647791425, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 97);
        assertLe(lots, 97 + 1);
        (lots, full) =
            LM.sizeEstimateLots(6000000000000000000000000, 5385005693797955164421405, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 5348);
        assertLe(lots, 5348 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1012702246779089621969152549, 537955614826831585807264514, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 3785500);
        assertLe(lots, 3785500 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1012702246779089621969152549, 43562193262586031509151373, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 7654321);
        assertLe(lots, 7654321 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1075623095973123247168418070, 814935527167321176327456717, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 1937388);
        assertLe(lots, 1937388 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 112405601673046562270500, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 67);
        assertLe(lots, 67 + 1);
        (lots, full) = LM.sizeEstimateLots(
            1075623095973123247168418070, 199227764255900058820811861, 7654321, 5e15, 1e12
        );
        assertEq(full, false);
        assertGe(lots, 6628785);
        assertLe(lots, 6628785 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000000, 72331780175098000404423989, 1000000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 415256);
        assertLe(lots, 415256 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 115063852219568504132671, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 43);
        assertLe(lots, 43 + 1);
        (lots, full) =
            LM.sizeEstimateLots(6000000000000000000000000, 2525006589520398605153109, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 30222);
        assertLe(lots, 30222 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 53692057955783530748293, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 577);
        assertLe(lots, 577 + 1);
        (lots, full) =
            LM.sizeEstimateLots(6000000000000000000000000, 2413157275808914553448043, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 31195);
        assertLe(lots, 31195 + 1);
        (lots, full) =
            LM.sizeEstimateLots(120000000000000000000000, 82977217091860497830658, 1000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 322);
        assertLe(lots, 322 + 1);
        (lots, full) =
            LM.sizeEstimateLots(6000000000000000000000000, 3914585003034228155981994, 50000, 5e15, 1e12);
        assertEq(full, false);
        assertGe(lots, 18136);
        assertLe(lots, 18136 + 1);
    }

    function test_diffBankruptcy() public pure {
        uint16 t;
        bool ok;
        (t, ok) = LM.bankruptcyTick(
            -501381,
            14410,
            -65000000000000000000000000,
            706478464531148959,
            14410000000000000000000,
            3000000000000000000000000
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            947093,
            376936,
            529000000000000000000000000,
            91596542757776695,
            376936000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            -1407962,
            130792,
            225000000000000000000000000,
            226008829198291340,
            130792000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            1334365,
            700040,
            237000000000000000000000000,
            109649333676105345,
            700040000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            78954,
            56614,
            -419000000000000000000000000,
            496453456216986145,
            56614000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            1211942,
            944799,
            -610000000000000000000000000,
            62168812470954968,
            944799000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 631);
        (t, ok) = LM.bankruptcyTick(
            -596403,
            127881,
            411000000000000000000000000,
            236388556253945940,
            127881000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 999);
        (t, ok) = LM.bankruptcyTick(
            -178006,
            19018,
            532000000000000000000000000,
            434225647190641095,
            19018000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 999);
        (t, ok) = LM.bankruptcyTick(
            -460980,
            328907,
            505000000000000000000000000,
            942696389622695196,
            328907000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 999);
        (t, ok) = LM.bankruptcyTick(
            1591984,
            807553,
            -644000000000000000000000000,
            900283190992882542,
            807553000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            895489,
            580009,
            674000000000000000000000000,
            87368171493862261,
            580009000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            1396136,
            1372073,
            -685000000000000000000000000,
            542138721589853188,
            1372073000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 494);
        (t, ok) = LM.bankruptcyTick(
            921145,
            5800,
            -103000000000000000000000000,
            459963056816102919,
            5800000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            -715654, 75462, -349000000000000000000000000, 205197022082885967, 75462000000000000000000, 0
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            1106642, 1038477, 68000000000000000000000000, 472892503662870671, 1038477000000000000000000, 0
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            -1267087,
            657697,
            -120000000000000000000000000,
            882829754417256280,
            657697000000000000000000,
            2000000000000000000000000
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            -1952025,
            559158,
            539000000000000000000000000,
            84645682399731722,
            559158000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 744);
        (t, ok) = LM.bankruptcyTick(
            -1423536,
            1401079,
            276000000000000000000000000,
            10281078899009338,
            1401079000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 192);
        (t, ok) = LM.bankruptcyTick(
            -264585,
            119260,
            235000000000000000000000000,
            441616745342811387,
            119260000000000000000000,
            3000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 999);
        (t, ok) = LM.bankruptcyTick(
            -397923,
            206571,
            153000000000000000000000000,
            257055230942396292,
            206571000000000000000000,
            3000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 487);
        (t, ok) = LM.bankruptcyTick(
            -1582385, 169072, -683000000000000000000000000, 804545218570048783, 169072000000000000000000, 0
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            -391858,
            10470,
            -76000000000000000000000000,
            497625731343319314,
            10470000000000000000000,
            3000000000000000000000000
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            -1752417, 1215594, 455000000000000000000000000, 264849608629865331, 1215594000000000000000000, 0
        );
        assertEq(ok, true);
        assertEq(t, 256);
        (t, ok) = LM.bankruptcyTick(
            54789, 10424, -19000000000000000000000000, 901998717903569845, 10424000000000000000000, 0
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            387038,
            246869,
            -29000000000000000000000000,
            441775609005934439,
            246869000000000000000000,
            1000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            -1061267,
            1037748,
            -25000000000000000000000000,
            705282158730801448,
            1037748000000000000000000,
            2000000000000000000000000
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            -1323076, 961538, 51000000000000000000000000, 586881758635377081, 961538000000000000000000, 0
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            544911,
            511747,
            89000000000000000000000000,
            539361934014076453,
            511747000000000000000000,
            4000000000000000000000000
        );
        assertEq(ok, true);
        assertEq(t, 1);
        (t, ok) = LM.bankruptcyTick(
            -1278157, 1241734, -431000000000000000000000000, 626153053452385462, 1241734000000000000000000, 0
        );
        assertEq(ok, false);
        (t, ok) = LM.bankruptcyTick(
            -1234861,
            793603,
            -697000000000000000000000000,
            51393662023503298,
            793603000000000000000000,
            2000000000000000000000000
        );
        assertEq(ok, false);
    }

    function test_diffStage() public pure {
        LC.StageView memory v;
        v = LC.deriveStage(4956000, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4954999, 5000000, 4950000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4955000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4996399, 5000000, 4950000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4955000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4996400, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4954999, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4954999, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4954999, 5000000, 4998000, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4996399, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(5000500, 5000000, 4998000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4956000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4999999, 5000000, 4998000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4999999, 5000000, 4998000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4956000, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4996400, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4996400, 5000000, 4998000, false, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(5000000, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4996400, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4956800, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 2);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4954999, 5000000, 4998000, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4955000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4996400, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4955000, 5000000, 4998000, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(5000500, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4999999, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4956801, 5000000, 4950000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4956000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4956800, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 2);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4999999, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4955000, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4956801, 5000000, 4950000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4956000, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(5000000, 5000000, 4998000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4996400, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(5000001, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4955000, 5000000, 0, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4996400, 5000000, 4950000, true, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4954999, 5000000, 4998000, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(5000000, 5000000, 4998000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4955000, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4996399, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 2);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4955000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4956801, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 2);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(5000000, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4996399, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 2);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4956801, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(5000500, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4996399, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4955000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 1);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(4956801, 5000000, 4998000, true, false);
        assertEq(uint8(v.stage), 3);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
        v = LC.deriveStage(4900000, 5000000, 0, false, false);
        assertEq(uint8(v.stage), 0);
        assertEq(v.fullBackingByTime, false);
        assertEq(v.fundingFrozen, false);
        v = LC.deriveStage(5000500, 5000000, 4950000, false, false);
        assertEq(uint8(v.stage), 4);
        assertEq(v.fullBackingByTime, true);
        assertEq(v.fundingFrozen, true);
    }

    function _book(uint256 i) internal pure returns (OA.OrderSums memory s) {
        s = OA.emptySums();
        if (i == 0) {
            s = OA.addOrder(s, true, 3, 620, 0);
            s = OA.addOrder(s, false, 2, 580, 0);
            s = OA.addOrder(s, false, 1, 600, 0);
        }
        if (i == 1) {
            s = OA.addOrder(s, true, 4, 590, 0);
            s = OA.addOrder(s, true, 2, 640, 0);
            s = OA.addOrder(s, false, 1, 700, 0);
        }
        if (i == 2) {
            s = OA.addOrder(s, false, 4, 610, 0);
            s = OA.addOrder(s, false, 3, 560, 0);
            s = OA.addOrder(s, true, 1, 600, 0);
        }
    }

    function _cov(int256 c, int256 x, OA.OrderSums memory s)
        internal
        pure
        returns (OA.CoverageInput memory v)
    {
        int256 e0 = c - int256(s.feeCapQ) - int256(s.bidValueQ);
        int256 e1 = c - int256(s.feeCapQ) + int256(UD) * x - int256(UD * s.askLots) + int256(s.askValueQ);
        v.d0Q = e0 < 0 ? uint256(-e0) : 0;
        v.d1Q = e1 < 0 ? uint256(-e1) : 0;
        v.deficitCapQ = 2000 * 1e24;
        v.marketOk = true;
    }

    function _a(uint256 book, int256 x, int256 cash, bool refOk, bool refSafe) internal pure {
        OA.OrderSums memory s = _book(book);
        (bool ok,) = OA.admit(
            OA.Account(cash, x), s, OA.Pricing(6e17, 3600, 0), RiskFixture.profile(5, true), _cov(cash, x, s)
        );
        if (ok) {
            assertTrue(refOk, "Solidity admits only what the reference admits");
            assertTrue(refSafe, "every admitted prefix passes reference enumeration");
        }
    }

    function test_diffAdmission() public pure {
        _a(0, -3, -3000000000000000000000, false, false);
        _a(0, -3, -2000000000000000000000, false, false);
        _a(0, -3, -1000000000000000000000, false, false);
        _a(0, -3, 0, false, false);
        _a(0, -3, 1000000000000000000000, false, false);
        _a(0, -3, 2000000000000000000000, false, false);
        _a(0, -3, 3000000000000000000000, false, false);
        _a(0, -3, 4000000000000000000000, false, false);
        _a(0, -3, 5000000000000000000000, true, true);
        _a(0, 0, -3000000000000000000000, false, false);
        _a(0, 0, -2000000000000000000000, false, false);
        _a(0, 0, -1000000000000000000000, false, false);
        _a(0, 0, 0, false, false);
        _a(0, 0, 1000000000000000000000, false, false);
        _a(0, 0, 2000000000000000000000, true, true);
        _a(0, 0, 3000000000000000000000, true, true);
        _a(0, 0, 4000000000000000000000, true, true);
        _a(0, 0, 5000000000000000000000, true, true);
        _a(0, 2, -3000000000000000000000, false, false);
        _a(0, 2, -2000000000000000000000, false, false);
        _a(0, 2, -1000000000000000000000, false, false);
        _a(0, 2, 0, false, false);
        _a(0, 2, 1000000000000000000000, false, false);
        _a(0, 2, 2000000000000000000000, true, true);
        _a(0, 2, 3000000000000000000000, true, true);
        _a(0, 2, 4000000000000000000000, true, true);
        _a(0, 2, 5000000000000000000000, true, true);
        _a(1, -3, -3000000000000000000000, false, false);
        _a(1, -3, -2000000000000000000000, false, false);
        _a(1, -3, -1000000000000000000000, false, false);
        _a(1, -3, 0, false, false);
        _a(1, -3, 1000000000000000000000, false, false);
        _a(1, -3, 2000000000000000000000, false, false);
        _a(1, -3, 3000000000000000000000, false, false);
        _a(1, -3, 4000000000000000000000, true, true);
        _a(1, -3, 5000000000000000000000, true, true);
        _a(1, 0, -3000000000000000000000, false, false);
        _a(1, 0, -2000000000000000000000, false, false);
        _a(1, 0, -1000000000000000000000, false, false);
        _a(1, 0, 0, false, false);
        _a(1, 0, 1000000000000000000000, false, false);
        _a(1, 0, 2000000000000000000000, false, false);
        _a(1, 0, 3000000000000000000000, false, false);
        _a(1, 0, 4000000000000000000000, true, true);
        _a(1, 0, 5000000000000000000000, true, true);
        _a(1, 2, -3000000000000000000000, false, false);
        _a(1, 2, -2000000000000000000000, false, false);
        _a(1, 2, -1000000000000000000000, false, false);
        _a(1, 2, 0, false, false);
        _a(1, 2, 1000000000000000000000, false, false);
        _a(1, 2, 2000000000000000000000, false, false);
        _a(1, 2, 3000000000000000000000, false, false);
        _a(1, 2, 4000000000000000000000, true, true);
        _a(1, 2, 5000000000000000000000, true, true);
        _a(2, -3, -3000000000000000000000, false, false);
        _a(2, -3, -2000000000000000000000, false, false);
        _a(2, -3, -1000000000000000000000, false, false);
        _a(2, -3, 0, false, false);
        _a(2, -3, 1000000000000000000000, false, false);
        _a(2, -3, 2000000000000000000000, false, false);
        _a(2, -3, 3000000000000000000000, false, false);
        _a(2, -3, 4000000000000000000000, false, false);
        _a(2, -3, 5000000000000000000000, false, false);
        _a(2, 0, -3000000000000000000000, false, false);
        _a(2, 0, -2000000000000000000000, false, false);
        _a(2, 0, -1000000000000000000000, false, false);
        _a(2, 0, 0, false, false);
        _a(2, 0, 1000000000000000000000, false, false);
        _a(2, 0, 2000000000000000000000, false, false);
        _a(2, 0, 3000000000000000000000, true, true);
        _a(2, 0, 4000000000000000000000, true, true);
        _a(2, 0, 5000000000000000000000, true, true);
        _a(2, 2, -3000000000000000000000, false, false);
        _a(2, 2, -2000000000000000000000, false, false);
        _a(2, 2, -1000000000000000000000, false, false);
        _a(2, 2, 0, false, false);
        _a(2, 2, 1000000000000000000000, true, true);
        _a(2, 2, 2000000000000000000000, true, true);
        _a(2, 2, 3000000000000000000000, true, true);
        _a(2, 2, 4000000000000000000000, true, true);
        _a(2, 2, 5000000000000000000000, true, true);
    }
}
