// Generated by scripts/sync-abis.ts from oracle/abi/IERC165.json (sha256 4eb64f51906e1cfc53f24b83d8439873c3b0ac71e7e01d9f442f1ff3c9291e88). Do not edit.
export const IERC165Abi = [
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  }
] as const
