// Generated by scripts/sync-abis.ts from oracle/abi/IKeeperRouter.json (sha256 57861243a45555fae80eca614c838ba0087fd03ecc647a05e6248495c1c4c225). Do not edit.
export const IKeeperRouterAbi = [
  {
    "type": "function",
    "name": "assertMany",
    "inputs": [
      {
        "name": "ids",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "asserted",
        "type": "bool[]",
        "internalType": "bool[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "finalizeMany",
    "inputs": [
      {
        "name": "ids",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "statuses",
        "type": "uint8[]",
        "internalType": "enum FinalizeStatus[]"
      },
      {
        "name": "reverted",
        "type": "bool[]",
        "internalType": "bool[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "haltAndRequest",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "halted",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "requested",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  }
] as const
