// Generated by scripts/sync-abis.ts from oracle/abi/IOptimisticOracleV3CallbackRecipient.json (sha256 dff38de67b11b8c4201ce2674e605b7755cae15e831d5e22fae07163a236b9cd). Do not edit.
export const IOptimisticOracleV3CallbackRecipientAbi = [
  {
    "type": "function",
    "name": "assertionDisputedCallback",
    "inputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assertionResolvedCallback",
    "inputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "assertedTruthfully",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const
