// Generated by scripts/sync-abis.ts from oracle/abi/IResolutionOracle.json (sha256 3ad6c7f782d5388b7233ee3d5d3210087b01335b5e05dfbc013c299ceed962cc). Do not edit.
export const IResolutionOracleAbi = [
  {
    "type": "function",
    "name": "activateTrustSet",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "activeTrustSetId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assertProposal",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "asserted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "bondFor",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createTrustSet",
    "inputs": [
      {
        "name": "t",
        "type": "tuple",
        "internalType": "struct TrustSetInput",
        "components": [
          {
            "name": "forwarder",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "production",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "workflowIds",
            "type": "bytes32[2]",
            "internalType": "bytes32[2]"
          },
          {
            "name": "workflowOwner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "workflowName",
            "type": "bytes10",
            "internalType": "bytes10"
          },
          {
            "name": "runnerAttestor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "committee",
            "type": "address[]",
            "internalType": "address[]"
          },
          {
            "name": "threshold",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "watchdog",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "venue",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "escalateToL2",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "changed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "evidenceURIOf",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "expireEarly",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "changed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "finalizeMarket",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum FinalizeStatus"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getL1Job",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "state",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "spec",
        "type": "tuple",
        "internalType": "struct FeedSpec",
        "components": [
          {
            "name": "urlTemplate",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "urlParam",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "authRef",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "finalPath",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "finalValue",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "valuePath",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "valueType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "op",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "target",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "bufferSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutSecs",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "allowList",
        "type": "string[]",
        "internalType": "string[]"
      },
      {
        "name": "specHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getResolution",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Resolution",
        "components": [
          {
            "name": "state",
            "type": "uint8",
            "internalType": "enum RState"
          },
          {
            "name": "proposed",
            "type": "uint8",
            "internalType": "enum Outcome"
          },
          {
            "name": "path",
            "type": "uint8",
            "internalType": "enum Path"
          },
          {
            "name": "attempts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rejectedMask",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "outcome",
            "type": "uint8",
            "internalType": "enum Outcome"
          },
          {
            "name": "finalReason",
            "type": "uint8",
            "internalType": "enum FinalReason"
          },
          {
            "name": "voided",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "haltedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "voidDeadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "l2StartedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "retryOpensAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "earlyStartedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastRequestAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "requestCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "trustSetId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "globalsVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "oiHaltLots",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "valueHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "assertionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "assertionVenue",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bond",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "rewardAtoms",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "groupState",
    "inputs": [
      {
        "name": "groupId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GroupState",
        "components": [
          {
            "name": "yesLockHolder",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "finalYes",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "haltScheduled",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "changed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hashPanelResult",
    "inputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct PanelResult",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "phase",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "attempt",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "labels",
            "type": "uint8[3]",
            "internalType": "uint8[3]"
          },
          {
            "name": "calibratedBps",
            "type": "uint16[3]",
            "internalType": "uint16[3]"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURIHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gateHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "flags",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "trustSetId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashReviewedProposal",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct ReviewedProposal",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "outcome",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURIHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "noteHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "attempt",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rejectedMask",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "early",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "trustSetId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initResolution",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isMemberRevoked",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "member",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSimRelayer",
    "inputs": [
      {
        "name": "relayer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastHeartbeat",
    "inputs": [
      {
        "name": "watchdog",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "livenessFor",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lockProduction",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "onReport",
    "inputs": [
      {
        "name": "metadata",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "report",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openAfterDeadline",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "changed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "proposePermissionless",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "outcome",
        "type": "uint8",
        "internalType": "enum Outcome"
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "assertionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renderClaim",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requestEarlyCheck",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestResolution",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "emitted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeAttestor",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeCommitteeMember",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "member",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeWatchdog",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeWorkflowId",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "workflowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSimForwarder",
    "inputs": [
      {
        "name": "forwarder",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSimRelayer",
    "inputs": [
      {
        "name": "relayer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "simForwarder",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "simMode",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitPanelProposal",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct PanelResult",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "phase",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "attempt",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "labels",
            "type": "uint8[3]",
            "internalType": "uint8[3]"
          },
          {
            "name": "calibratedBps",
            "type": "uint16[3]",
            "internalType": "uint16[3]"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURIHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gateHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "flags",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "trustSetId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitPanelResult",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct PanelResult",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "phase",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "attempt",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "labels",
            "type": "uint8[3]",
            "internalType": "uint8[3]"
          },
          {
            "name": "calibratedBps",
            "type": "uint16[3]",
            "internalType": "uint16[3]"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURIHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gateHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "flags",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "trustSetId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "routedTo",
        "type": "uint8",
        "internalType": "enum RState"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitReviewedProposal",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct ReviewedProposal",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "outcome",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURIHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "noteHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "attempt",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rejectedMask",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "early",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "trustSetId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "sigs",
        "type": "tuple[]",
        "internalType": "struct Sig[]",
        "components": [
          {
            "name": "signer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "signature",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "syncAssertion",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "changed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "trustSet",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct TrustSet",
        "components": [
          {
            "name": "cfg",
            "type": "tuple",
            "internalType": "struct TrustSetInput",
            "components": [
              {
                "name": "forwarder",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "production",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "workflowIds",
                "type": "bytes32[2]",
                "internalType": "bytes32[2]"
              },
              {
                "name": "workflowOwner",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "workflowName",
                "type": "bytes10",
                "internalType": "bytes10"
              },
              {
                "name": "runnerAttestor",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "committee",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "threshold",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "watchdog",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venue",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "workflowIdRevoked",
            "type": "bool[2]",
            "internalType": "bool[2]"
          },
          {
            "name": "attestorRevoked",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "watchdogRevoked",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "voidMarket",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "changed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "watchdogHeartbeat",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "watchdogOf",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Asserted",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "venue",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "outcome",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Outcome"
      },
      {
        "name": "path",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Path"
      },
      {
        "name": "bond",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "liveness",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "asserter",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssertionRejected",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "outcome",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Outcome"
      },
      {
        "name": "rejectedMask",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "retryOpensAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Disputed",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "assertionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EarlyCheckCleared",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EarlyCheckRequested",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Finalized",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "outcome",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Outcome"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum FinalReason"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GroupConflict",
    "inputs": [
      {
        "name": "groupId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GroupLock",
    "inputs": [
      {
        "name": "groupId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "acquired",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HaltRecorded",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "haltedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "oiHaltLots",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "voidDeadline",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "trustSetId",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "early",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PanelNotYet",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "attempt",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PanelResultAccepted",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "phase",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Phase"
      },
      {
        "name": "labels",
        "type": "uint8[3]",
        "indexed": false,
        "internalType": "uint8[3]"
      },
      {
        "name": "calibratedBps",
        "type": "uint16[3]",
        "indexed": false,
        "internalType": "uint16[3]"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "routedTo",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RState"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProductionLocked",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalRecorded",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "outcome",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Outcome"
      },
      {
        "name": "path",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Path"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "attempt",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposedL1",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "outcome",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Outcome"
      },
      {
        "name": "observedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "valueHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ResolutionInitialized",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ResolutionRequested",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "requestedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "requestCount",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SimForwarderSet",
    "inputs": [
      {
        "name": "forwarder",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SimRelayerSet",
    "inputs": [
      {
        "name": "relayer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "allowed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StateChanged",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "from",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RState"
      },
      {
        "name": "to",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RState"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TrustSetActivated",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TrustSetCreated",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "production",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TrustSetRevoked",
    "inputs": [
      {
        "name": "setId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "what",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "detail",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Voided",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum FinalReason"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WatchdogHeartbeat",
    "inputs": [
      {
        "name": "watchdog",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadMetadata",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPayload",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadReport",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadTrustSet",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "EngineCallFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpiryAfterVoidDeadline",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GateClosed",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "GroupYesTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxAttempts",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoActiveTrustSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoFeed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCommitteeMember",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotEnoughSignatures",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSupported",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OutcomeNotAllowed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProductionSetRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SignatureExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SignersNotSorted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SimModeOff",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TreasuryShort",
    "inputs": [
      {
        "name": "need",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "have",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownMarket",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongState",
    "inputs": [
      {
        "name": "have",
        "type": "uint8",
        "internalType": "enum RState"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongWorkflow",
    "inputs": []
  }
] as const
