// Generated by scripts/sync-abis.ts from oracle/abi/KeeperRouter.json (sha256 48216beb808b680dd633dcdb0b4f68586e40172f0d9788429d13518a2e65d83a). Do not edit.
export const KeeperRouterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "oracle_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assertMany",
    "inputs": [
      {
        "name": "ids",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "asserted",
        "type": "bool[]",
        "internalType": "bool[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "finalizeMany",
    "inputs": [
      {
        "name": "ids",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "statuses",
        "type": "uint8[]",
        "internalType": "enum FinalizeStatus[]"
      },
      {
        "name": "reverted",
        "type": "bool[]",
        "internalType": "bool[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "haltAndRequest",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "halted",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "requested",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "oracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IResolutionOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const
