// Generated by scripts/sync-abis.ts from oracle/abi/MarketFactory.json (sha256 16be84412a94218373d5706cb2ff238cc0432bb28f075ff457c68db480bde210). Do not edit.
export const MarketFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "treasury_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "codeStore_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "codeStoreTail_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "creationCodeHash_",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "codeStore",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "codeStoreHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "codeStoreTail",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "codeStoreTailHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "collateralVault",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract CollateralVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "creationCodeHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployMarket",
    "inputs": [
      {
        "name": "listing",
        "type": "tuple",
        "internalType": "struct IMarketConfig.Listing",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "resolutionAuthority",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "monitor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "governance",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "scheduledT",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "listedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sourceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rulesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "invalidRule",
            "type": "tuple",
            "internalType": "struct IMarketConfig.InvalidRule",
            "components": [
              {
                "name": "fallbackListed",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "captureGraceSecs",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "fallbackPriceWad",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "voidSecs",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "template",
            "type": "uint8",
            "internalType": "enum MarginMath.Template"
          },
          {
            "name": "deploymentCapX",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxTraders",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "indexSourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "indexSigner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "indexRulesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "depthNLots",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxSpreadWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bootstrapBandWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minOrderLots",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxOrderLots",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxLiqLotsPerBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "fundingEnabled",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "engineInit",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "engine",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "engineOf",
    "inputs": [
      {
        "name": "marketId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "engine",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolutionAuthority",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "MarketDeployed",
    "inputs": [
      {
        "name": "marketId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "engine",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "vault",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "listingHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DeploymentFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDependency",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidEngineCode",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidListing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ListingHashMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedEngineInit",
    "inputs": []
  }
] as const
