"""Emit independent Fraction-derived vectors. Never execute Solidity here."""
import json,random
from fractions import Fraction as F
from pathlib import Path
from reference.a.ledger import Account,equity
from reference.a.premium_integral import cumulative,cumulative_charge
from reference.common.units import Q,REFERENCE_SEED

def export(root):
    rng=random.Random(REFERENCE_SEED)
    ledger=[];premium=[]
    for _ in range(64):
        n=rng.randint(-10**9,10**9);c=rng.randint(-10**12,10**12)*Q;p=rng.randint(0,Q)
        e=int(equity(Account(n,c),F(p,Q)))
        ledger.append([c,n,p,e,max(e,0)//Q])
    for _ in range(32):
        n=rng.randint(-100000,100000);c=rng.randint(-100000000,100000000)*Q
        rate=rng.randint(-10**12,10**12);end=rng.randint(1,3600);stop=rng.randint(0,end);expiry=rng.randint(0,end)
        h0=10**14;h1=10**14;load=Q
        exact=cumulative(c,n,rate,0,end,stop,expiry,h0,h1,load)
        premium.append([c,n,rate,end,stop,expiry,cumulative_charge(exact)])
    output=root/'reference/fixtures/a/vectors.json';output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(json.dumps({'seed':hex(REFERENCE_SEED),'ledger':[[str(x) for x in r] for r in ledger],
                                  'premium':[[str(x) for x in r] for r in premium]},indent=2)+'\n')
    source=['// SPDX-License-Identifier: MIT','pragma solidity ^0.8.30;','// Generated by reference/a/export_vectors.py using exact Fraction arithmetic.','library ReferenceVectors {']
    for name,rows,width in [('ledger',ledger,5),('premium',premium,7)]:
        source.append(f'function {name}() internal pure returns(int256[{width}][] memory v) {{ v=new int256[{width}][]({len(rows)});')
        for i,row in enumerate(rows):source.append(f'v[{i}]=[int256({row[0]}),'+','.join(str(x) for x in row[1:])+'];')
        source.append('}')
    source.append('}')
    path=root/'contracts/test/math/A/ReferenceVectors.sol';path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text('\n'.join(source)+'\n')

if __name__=='__main__':export(Path(__file__).resolve().parents[2])
