// Regenerates oracle/abi/<Name>.json, oracle/abi/SHA256SUMS and src/abi/<Name>.ts from `forge inspect`.
// Run after any ABI change; test/abi.test.ts fails on drift.
//
//   bun run sync-abis
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ABI_DIR, ORACLE_ROOT, SOURCES } from '../src/abi/sources'

export const canonicalAbiText = (text: string): string => text.replaceAll('\r\n', '\n')
export const abiTextHash = (text: string): string => createHash('sha256').update(canonicalAbiText(text)).digest('hex')

export function forgeInspect(source: string, name: string): string {
  const p = Bun.spawnSync(['forge', 'inspect', `${source}:${name}`, 'abi', '--json'], { cwd: ORACLE_ROOT, stdout: 'pipe', stderr: 'pipe' })
  if (p.exitCode !== 0) throw new Error(`forge inspect ${source}:${name} failed: ${p.stderr.toString().slice(-400)}`)
  return canonicalAbiText(p.stdout.toString())
}

export function tsModule(name: string, json: string): string {
  return `// Generated by scripts/sync-abis.ts from oracle/abi/${name}.json (sha256 ${abiTextHash(json)}). Do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(JSON.parse(json), null, 2)} as const\n`
}

if (import.meta.main) {
  for (const { name, source } of SOURCES) {
    const json = forgeInspect(source, name)
    writeFileSync(join(ABI_DIR, `${name}.json`), json)
    writeFileSync(new URL(`../src/abi/${name}.ts`, import.meta.url), tsModule(name, json))
  }
  const files = readdirSync(ABI_DIR).filter((f) => f.endsWith('.json')).sort()
  writeFileSync(join(ABI_DIR, 'SHA256SUMS'), files.map((f) => `${abiTextHash(readFileSync(join(ABI_DIR, f), 'utf8'))}  ${f}`).join('\n') + '\n')
  const index = SOURCES.map(({ name }) => `export { ${name}Abi } from './${name}'`).join('\n') + '\n'
  writeFileSync(new URL('../src/abi/index.ts', import.meta.url), `// Generated by scripts/sync-abis.ts. Do not edit.\n${index}`)
  console.log(`wrote ${SOURCES.length} ABIs, SHA256SUMS (${files.length} files) and src/abi/`)
}
