// Task O30.1: the ABI snapshot and its SDK copy (plan §9). For every oracle interface and contract it writes
// `forge inspect <source>:<Name> abi --json` to oracle/abi/<Name>.json, regenerates oracle/abi/SHA256SUMS, and
// writes src/abi/<Name>.ts (`as const` for viem's types) stamped with the JSON's sha256. Run after any change to
// an ABI; test/abi.test.ts fails until it is run (drift between the sources, the snapshot and the SDK).
//
//   cd oracle/packages/oracle-sdk && bun run sync-abis
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ABI_DIR, ORACLE_ROOT, SOURCES } from '../src/abi/sources'

const sha256 = (b: Uint8Array | string) => createHash('sha256').update(b).digest('hex')

export function forgeInspect(source: string, name: string): string {
  const p = Bun.spawnSync(['forge', 'inspect', `${source}:${name}`, 'abi', '--json'], { cwd: ORACLE_ROOT, stdout: 'pipe', stderr: 'pipe' })
  if (p.exitCode !== 0) throw new Error(`forge inspect ${source}:${name} failed: ${p.stderr.toString().slice(-400)}`)
  return p.stdout.toString()
}

export function tsModule(name: string, json: string): string {
  return `// Generated by scripts/sync-abis.ts from oracle/abi/${name}.json (sha256 ${sha256(json)}). Do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(JSON.parse(json), null, 2)} as const\n`
}

if (import.meta.main) {
  for (const { name, source } of SOURCES) {
    const json = forgeInspect(source, name)
    writeFileSync(join(ABI_DIR, `${name}.json`), json)
    writeFileSync(new URL(`../src/abi/${name}.ts`, import.meta.url), tsModule(name, json))
  }
  const files = readdirSync(ABI_DIR).filter((f) => f.endsWith('.json')).sort()
  writeFileSync(join(ABI_DIR, 'SHA256SUMS'), files.map((f) => `${sha256(readFileSync(join(ABI_DIR, f)))}  ${f}`).join('\n') + '\n')
  const index = SOURCES.map(({ name }) => `export { ${name}Abi } from './${name}'`).join('\n') + '\n'
  writeFileSync(new URL('../src/abi/index.ts', import.meta.url), `// Generated by scripts/sync-abis.ts. Do not edit.\n${index}`)
  console.log(`wrote ${SOURCES.length} ABIs, SHA256SUMS (${files.length} files) and src/abi/`)
}
