// Generated by scripts/gen-abis.mjs from oracle/abi/MarketRegistry.json. Do not edit.
export const marketRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "oracle_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "treasury_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "factory_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "usdc_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "lister_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "authRefKnown",
    "inputs": [
      {
        "name": "authRef",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "category",
    "inputs": [
      {
        "name": "categoryId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Category",
        "components": [
          {
            "name": "gateHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "u95Bps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "sampleN",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "validated",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "validatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createMarket",
    "inputs": [
      {
        "name": "m",
        "type": "tuple",
        "internalType": "struct MarketInput",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "question",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "rules",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "claimTemplate",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "windowStart",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "tau",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "groupId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "groupExclusive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hasFeed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "feed",
            "type": "tuple",
            "internalType": "struct FeedSpec",
            "components": [
              {
                "name": "urlTemplate",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "urlParam",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "authRef",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "finalPath",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "finalValue",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "valuePath",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "valueType",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "decimals",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "op",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "target",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "bufferSecs",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "l1TimeoutSecs",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "allowList",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "ai",
            "type": "tuple",
            "internalType": "struct AIConfig",
            "components": [
              {
                "name": "allowListPtr",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "modelIdHashes",
                "type": "bytes32[3]",
                "internalType": "bytes32[3]"
              },
              {
                "name": "promptHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "calibratorHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "categoryId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "highConfBps",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "uma",
            "type": "tuple",
            "internalType": "struct UMAConfig",
            "components": [
              {
                "name": "bondCurrency",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "minBond",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bondBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "livenessL1",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "livenessAuto",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "livenessReviewed",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "claimTemplatePtr",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "l2DeadlineSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "voidSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "monitor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "oiCapLots",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dryRunHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ambiguityLogHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "engineListing",
        "type": "tuple",
        "internalType": "struct IMarketConfig.Listing",
        "components": [
          {
            "name": "marketId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "resolutionAuthority",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "monitor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "governance",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "scheduledT",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "listedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sourceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rulesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "invalidRule",
            "type": "tuple",
            "internalType": "struct IMarketConfig.InvalidRule",
            "components": [
              {
                "name": "fallbackListed",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "captureGraceSecs",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "fallbackPriceWad",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "voidSecs",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "template",
            "type": "uint8",
            "internalType": "enum MarginMath.Template"
          },
          {
            "name": "deploymentCapX",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxTraders",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "indexSourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "indexSigner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "indexRulesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "depthNLots",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxSpreadWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bootstrapBandWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minOrderLots",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxOrderLots",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "maxLiqLotsPerBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "fundingEnabled",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "engineInit",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "engine",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAIConfig",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AIConfig",
        "components": [
          {
            "name": "allowListPtr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "modelIdHashes",
            "type": "bytes32[3]",
            "internalType": "bytes32[3]"
          },
          {
            "name": "promptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "calibratorHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "categoryId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "highConfBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAllowList",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "hosts",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getClaimTemplate",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getFeedSpec",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct FeedSpec",
        "components": [
          {
            "name": "urlTemplate",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "urlParam",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "authRef",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "finalPath",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "finalValue",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "valuePath",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "valueType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "op",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "target",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "bufferSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutSecs",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketCore",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct MarketCore",
        "components": [
          {
            "name": "engine",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "questionPtr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "rulesPtr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "listedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowStart",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "windowEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "tau",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "groupId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "groupExclusive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hasFeed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "l2DeadlineSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "voidSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "retryWindowSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "earlyTtlSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "monitor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "oiCapLots",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "rulesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "specHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gateHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getQuestion",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRules",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSpecHash",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getUMAConfig",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct UMAConfig",
        "components": [
          {
            "name": "bondCurrency",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minBond",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bondBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "livenessL1",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "livenessAuto",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "livenessReviewed",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "claimTemplatePtr",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "globals",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Globals",
        "components": [
          {
            "name": "minHorizonSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxListingHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxVoidSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l2MinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l2MaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bufferMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bufferMaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutMaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bondBpsFloor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "highConfFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxClaimBytes",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "dvmRoundSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "dvmMaxRolls",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reviewTargetSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "voidSlackSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "retryWindowSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "earlyTtlSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minRequestIntervalSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "heartbeatMaxAgeSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deltaPmaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "nMin",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "reviewLimitAtoms",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposerRewardAtoms",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "globalsAt",
    "inputs": [
      {
        "name": "version",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Globals",
        "components": [
          {
            "name": "minHorizonSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxListingHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxVoidSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l2MinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l2MaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bufferMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bufferMaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutMaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bondBpsFloor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "highConfFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxClaimBytes",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "dvmRoundSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "dvmMaxRolls",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reviewTargetSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "voidSlackSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "retryWindowSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "earlyTtlSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minRequestIntervalSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "heartbeatMaxAgeSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deltaPmaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "nMin",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "reviewLimitAtoms",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposerRewardAtoms",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "globalsVersion",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "groupInfo",
    "inputs": [
      {
        "name": "groupId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GroupInfo",
        "components": [
          {
            "name": "exists",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exclusive",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isListed",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lister",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minVoidSecs",
    "inputs": [
      {
        "name": "hasFeed",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "l1TimeoutSecs",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "l2DeadlineSecs",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "livenessReviewed",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "oracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "providerAllowed",
    "inputs": [
      {
        "name": "host",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAuthRef",
    "inputs": [
      {
        "name": "authRef",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "known",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setCategory",
    "inputs": [
      {
        "name": "categoryId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "gateHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "u95Bps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "sampleN",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "validated",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFactory",
    "inputs": [
      {
        "name": "factory_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGlobals",
    "inputs": [
      {
        "name": "g",
        "type": "tuple",
        "internalType": "struct Globals",
        "components": [
          {
            "name": "minHorizonSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxListingHorizon",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxVoidSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l2MinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l2MaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bufferMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bufferMaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "l1TimeoutMaxSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tMinSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "bondBpsFloor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "highConfFloorBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxClaimBytes",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "dvmRoundSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "dvmMaxRolls",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reviewTargetSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "voidSlackSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "retryWindowSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "earlyTtlSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minRequestIntervalSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "heartbeatMaxAgeSecs",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deltaPmaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "nMin",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "reviewLimitAtoms",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposerRewardAtoms",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLister",
    "inputs": [
      {
        "name": "lister_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProvider",
    "inputs": [
      {
        "name": "host",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "usdc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AuthRefSet",
    "inputs": [
      {
        "name": "authRef",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "known",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CategorySet",
    "inputs": [
      {
        "name": "categoryId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "gateHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "u95Bps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "sampleN",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "validated",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FactorySet",
    "inputs": [
      {
        "name": "factory",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GlobalsSet",
    "inputs": [
      {
        "name": "version",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "globalsHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ListerSet",
    "inputs": [
      {
        "name": "lister",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketListed",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "engine",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tau",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "hasFeed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "groupId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "rulesHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "specHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "gateHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "umaConfigHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "dryRunHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "ambiguityLogHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProviderSet",
    "inputs": [
      {
        "name": "host",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "allowed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadAIConfig",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadAllowList",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadFeed",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadGlobals",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadTimes",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadUMAConfig",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "DuplicateMarket",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EarlyCheckOrGroupsDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EngineAlreadyHalted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GroupMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTemplate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ListingHashMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoActiveTrustSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoFactory",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
